-- AlterTable
ALTER TABLE "users" ALTER COLUMN "license_number" SET DATA TYPE VARCHAR(999),
ALTER COLUMN "license_state" SET DATA TYPE VARCHAR(999),
ALTER COLUMN "license_city" SET DATA TYPE VARCHAR(999),
ALTER COLUMN "license_country" SET DATA TYPE VARCHAR(999),
ALTER COLUMN "license_zip_code" SET DATA TYPE VARCHAR(999);
